### PR TITLE
Auth, wallet unlock separation, container updates

### LINKED ISSUE #8: Remove lnd-unlock service
Unlocking wallet is handled by https://github.com/getumbrel/umbrel-manager now

### LINKED ISSUE #9: Add umbrel-manager service
Add https://github.com/getumbrel/umbrel-manager container service to docker-compose.yml

### LINKED ISSUE #9: Create database directories for umbrel-manager
Add database directories used by https://github.com/getumbrel/umbrel-manager to store user password, encrypted seed, JWT public/private key, etc.

### LINKED ISSUE #10: Create database directories for umbrel-manager
Add database directories used by https://github.com/getumbrel/umbrel-manager to store user password, encrypted seed, JWT public/private key, etc.

### LINKED ISSUE #10: Add umbrel-manager service
Add https://github.com/getumbrel/umbrel-manager container service to docker-compose.yml

### LINKED ISSUE #11: Remove lnd-unlock service
Unlocking wallet is handled by https://github.com/getumbrel/umbrel-manager now

### PR DESCRIPTION
**Pull request by mayankchhabra**
### Changlog
- [x] Remove `lnd-unlock` container
- [x] Add `umbrel-manager` container
- [x] Create directory structure for `umbrel-manager`
- [x] Add `umbrel-dashboard` container
- [x] Update Nginx configuration w.r.t `umbrel-manager` and `umbrel-dashboard`

### Should be merged after:
- [x] `umbrel-manager` 0.1.0 is released
- [x] `umbrel-middleware` 0.1.0 is released
- [x] `umbrel-dashboard` 0.2.0 is released
- [x] https://github.com/getumbrel/umbrel-middleware/issues/20 is fixed

### Should be tested with:
- `getumbrel/umbrel-manager:v0.1.0.3` 
- `getumbrel/umbrel-middleware:v0.1.0.5` 
- `getumbrel/umbrel-dashboard:v0.2.0.3` 

---
Closes #9, resolves #10 and fixes #11.

### CODE REVIEW

**Comment by nolim1t** [comment]
is this ready to be tested?

**Comment by nolim1t** [comment]
or do we need to release the other versions

**Review by nolim1t — COMMENTED** [review]
LGTM

**Comment by mayankchhabra** [comment]
Not yet, just finishing up other containers. I'll update docker-compose.yml with test versions w.x.y.z for testing once all of them are up

**Comment by mayankchhabra** [comment]
Ok we're ready to test! I've updated `docker-compose.yml` with the latest w.x.y.z images and will revert back to x.y.z releases after we test it out. 

Deployed on https://testnet.getumbrel.com and no issues so far. I'll try it on my hardware node too.

Side note: If you're going to test on an existing umbrel node, don't forget to remove the existing lnd wallet because `umbrel-manager` will set up a new wallet.

**Comment by nolim1t** [comment]
I get ```"Unknown authentication strategy \"jwt\""```

**Comment by nolim1t** [comment]
versions

```
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS               NAMES
24253f01f7a8        getumbrel/middleware:v0.1.0.4       "docker-entrypoint.s…"   3 hours ago         Up 2 minutes                            umbrel_middleware_1
a01dcacbdfde        lncm/lnd:v0.9.2-root-experimental   "lnd"                    3 hours ago         Up 14 minutes                           umbrel_lnd_1
673c097af1c3        getumbrel/dashboard:v0.2.0.3        "docker-entrypoint.s…"   3 hours ago         Up 14 minutes                           umbrel_dashboard_1
2d81272cc9dd        lncm/bitcoind:v0.19.1               "bitcoind -zmqpubraw…"   3 hours ago         Up 9 minutes                            umbrel_bitcoin_1
7580652ff0c7        nginx:1.17.10                       "nginx -g 'daemon of…"   3 hours ago         Up 10 minutes                           umbrel_web_1
92d86f6e3332        getumbrel/manager:v0.1.0.3          "docker-entrypoint.s…"   3 hours ago         Up 14 minutes                           umbrel_manager_1
```

**Comment by nolim1t** [comment]
in your docker-compose file you have  ```image: getumbrel/dashboard:v0.2.0.3``` defined which I used however the original PR says test with ```getumbrel/umbrel-dashboard:v0.2.0.2```

**Comment by nolim1t** [comment]
getumbrel/umbrel-dashboard:v0.2.0.2 also doesnt work

**Comment by mayankchhabra** [comment]
> "Unknown authentication strategy \"jwt\""

Which container throws that error?

Updated PR comment, should be tested with `getumbrel/umbrel-dashboard:v0.2.0.3`

**Comment by nolim1t** [comment]
> > "Unknown authentication strategy "jwt""
> 
> Which container throws that error?


Error from browser.. but most likely dashboard container

**Comment by nolim1t** [comment]
Logfile trace from middleware logs after trying to log in

```
Error: Unknown authentication strategy "jwt"
    at attempt (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:190:39)
    at authenticate (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:367:7)
    at jwt (/usr/src/app/middlewares/auth.js:47:5)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
```
Screenshot from dashboard (private browsing window)

screenshot

**Comment by nolim1t** [comment]
Ok i think I found the issue. I'll retry again

**Comment by nolim1t** [comment]
```
/v1/lnd/wallet/unlock
NodeError: Invalid JWT
    at /usr/src/app/middlewares/auth.js:38:19
    at allFailed (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:107:18)
    at attempt (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:180:28)
    at JwtStrategy.strategy.fail (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:302:9)
    at /usr/src/app/node_modules/passport-jwt/lib/strategy.js:106:33
    at /usr/src/app/node_modules/jsonwebtoken/verify.js:133:14
    at getSecret (/usr/src/app/node_modules/jsonwebtoken/verify.js:90:14)
    at Object.module.exports [as verify] (/usr/src/app/node_modules/jsonwebtoken/verify.js:94:10)
    at Function.module.exports [as JwtVerifier] (/usr/src/app/node_modules/passport-jwt/lib/verify_jwt.js:4:16)
    at /usr/src/app/node_modules/passport-jwt/lib/strategy.js:104:25
```

**Comment by nolim1t** [comment]
Ok it seems to be working but have to restart the middleware container every time docker is restarted, which isn't really ideal

**Comment by nolim1t** [comment]
Some changes to the middleware container might be needed

https://github.com/getumbrel/umbrel-middleware/issues/20#issuecomment-633205449

We will also need to add some HTTP libraries for it to query the manager container

**Comment by nolim1t** [comment]
Pushed a tag with a command we can use in ```getumbrel/middleware:v0.1.0.5```

**Comment by nolim1t** [comment]
Update the docker-compose file with

```
        middleware:
                image: "getumbrel/middleware:v0.1.0.5"
                command: ["./wait-for-node-manager.sh", "localhost", "npm", "start"]
```

and this should fix any issues

**Comment by mayankchhabra** [comment]
Great! If you haven't encountered any other issues, then we're ready to merge https://github.com/getumbrel/umbrel-manager/pull/1 and release `umbrel-manager 0.1.0`.

After that, we can merge https://github.com/getumbrel/umbrel-middleware/pull/21 and release `umbrel-middleware 0.1.0`.

Then we can proceed to merge https://github.com/getumbrel/umbrel-dashboard/pull/60 and release `umbrel-dashboard 0.2.0`.

And then finally we'll be ready to merge this current PR #12 lol! 😅

**Comment by mayankchhabra** [comment]
Released
- [x] `umbrel-manager v0.1.0`
- [x] `umbrel-middleware v0.1.0`
- [x] `umbrel-dashboard v0.2.0`

Also deployed the new containers on [testnet](https://testnet.getumbrel.com) and everything looks OK.

@nolim1t can you also please test them? If all's OK, we're ready to merge 🚀

**Comment by nolim1t** [comment]
LGTM.. installed on my umbrel box

**Comment by mayankchhabra** [comment]
Ready to rock and roll! We should probably tag this as a v0.1.0 release for `umbrel-compose` too. What do you think?

**Pull request merged**
