### PR TITLE
Store TLS settings back to what it supposed to be

### PR DESCRIPTION
**Pull request by nolim1t**
Skipped over the last review but I'm Using these settings to develop needs to be in sync.

### CODE REVIEW

**Comment by mayankchhabra** [comment]
It doesn't work for me at all. :(
I've tried locally (mac amd64) and on a fresh install on RPi 4. The TLS settings don't work on either

**Comment by nolim1t** [comment]
are you using 0.10.1 ?

**Comment by mayankchhabra** [comment]
Which lnd docker image are you able to successfully use these options with?

**Comment by mayankchhabra** [comment]
> are you using 0.10.1 ?

Yes, `lncm/lnd:v0.10.1-experimental` (that is in the latest `docker-compose.yml`).

**Pull request closed without merging**
