### PR TITLE
Improvements for compose-framework

### PR DESCRIPTION
**Pull request by nolim1t**
Here are a list of changes

## Summary of changes

- [x] change HOME to PWD.
- [x] Update to lnd v0.10.0 without root experimental and remove references to TOR (get ready for tor passwords)
- [x] TOR container
- [x] Stop using host networking and use its own network (so everything is fully self contained)
- [x] Testnet support (and regtest support)

## Other stuff that I'd like to address

Done :)

### CODE REVIEW

**Comment by nolim1t** [comment]
Also want to add in the TOR container back in and full tor password support

**Comment by nolim1t** [comment]
Tor container added and no longer using host networking too.

Just have to get testnet support working

**Comment by nolim1t** [comment]
regtest is working, but would like to get to a stage where you can connect multiple LNDs together (now that PWD support is also working)

**Comment by mayankchhabra** [comment]
Great work @nolim1t! I reviewed and played out with it today. LGTM! Made some changes through #31

**Comment by nolim1t** [comment]
Tried to use hostnames for references and unfortnately it didnt work

**Comment by mayankchhabra** [comment]
No worries at all, we can go ahead with your current bridge networking setup as it's still better than using host networking and can look into overlay networks later.

**Comment by mayankchhabra** [comment]
Merged! Once again, great work @nolim1t 🚀

**Pull request merged**
