### PR TITLE
Partition utility (pre-release)

### PR DESCRIPTION
**Pull request by nolim1t**
Pre-release partition utility. 

Will need to tidy this up first (and make the code more robust too)

### CODE REVIEW

**Comment by nolim1t** [comment]
Ok I will need some help with testing. Please note the drive configuration you used.

## Test Cases

Please run the partitioner in ```contrib/partitioner``` folder (requires sudo) in these conditions:

* Drive bigger than 512GB (FAT32 formatted). Result: Should be reformatted as EXT4 and completely new. uuid in ```blkid``` output and ```/etc/fstab``` must match.
* Drive bigger than 512GB (FAT32 formatted) with ```bitcoin``` folder. Result: Should NOT format), however the whole structure will be preserved for now. uuid in ```blkid``` output and ```/etc/fstab``` must match.
* Any size drive with EXT4 configuration NO folders. Result: reformatted, and rebuilt.  uuid in ```blkid``` output and ```/etc/fstab``` must match.
* Existing drive with all folder structure. Can be any size. Result: Everything preserved. uuid in ```blkid``` output and ```/etc/fstab``` must match.
* Existing drive with all folder structure but with a ```.rekt``` file in the directory root. Can be any size. Result: Everything rebuilt. uuid in ```blkid``` output and ```/etc/fstab``` must match.

**Comment by nolim1t** [comment]
TODO list, tidy up code and also try to make use of native python functions rather than ```os.system```

**Comment by mayankchhabra** [comment]
## Test 1/5

**Drive size:** NTFS, 2TB, USB 3.0 HDD
**Drive's directory structure:** Contains existing files and directories but none are related to Umbrel.

---

➡️ After plugging in the drive (unmounted):

image

---

➡️ After running `partioner.py` (LGTM except it couldn't access `bitcoin.conf`):

image

## Checks

✅ Pass: Drive reformatted as `EXT4` after running `partitioner.py` and mounted to `/mnt/data`

image

---

✅Pass: UUID matches in `/etc/fstab`

image

---

✅Pass:  Data copied to `/mnt/data`

image

---

✅Pass: Symlinks created

image

---

❌ Fail: Disable pruning

Looks like it failed because `partitioner.py` couldn't access `bitcoin.conf` file

image

**Comment by mayankchhabra** [comment]
## Test 2/5

**Drive size:** EXT4, 2TB, USB 3.0 HDD
**Drive's directory structure:** Existing Umbrel drive with Umbrel's directory-structure.

---

➡️ After plugging in the drive (unmounted):

image

---

➡️ After running `partioner.py`:

image


## Checks

✅ Pass: Drive mounted to `/mnt/data/`

image

---

🟡 Unsure: UUID matches in `/etc/fstab`

But now there's a double-entry. Perhaps it should add a check to not update fstab in case the UUID has already been added?

image

---

✅ Pass: Data preserved after running `partitioner.py`

I also created a `.dontformat` file and a `dontformat/` directory on the drive before running `partioner.py` just to make sure that they still exist after running the partitioning utility. 

image

---

✅Pass: Symlinks created

image

---

❌ Fail: Disable pruning

Looks like it doesn't disable pruning in case an existing Umbrel drive is attached.

image

**Comment by mayankchhabra** [comment]
## Test 3/5

**Drive size:** EXT4, 2TB, USB 3.0 HDD
**Drive's directory structure:** Existing Umbrel drive with Umbrel's directory-structure **AND** a `.rekt` file.

---

➡️ After creating a `.rekt` file and unmounting the drive:

image

---

➡️ After running `partioner.py`:

image

## Checks

✅ Pass: Drive mounted to `/mnt/data/`

image

---

🟡 Unsure: UUID matches in `/etc/fstab`

The UUID of the drive has changed, but the previous invalid UUID entries still exist.

image

---

❌ Fail: Delete previous directories/files and create new ones.

Previous directories/files were indeed deleted, but the recreated directories have symlinks which point to themselves, creating a loop.

image

---

❌ Fail: Symlinks created

The symlinks in `/home/umbrel/` are broken too because the recreated directories on `/mnt/data/` have looped symlinks that point to themselves.

image

---

❌ Fail: Disable pruning

No `/home/umbrel/bitcoin/bitcoin.conf` file anymore due to the symlink loop 😅

image

**Comment by mayankchhabra** [comment]
How's this coming along @nolim1t? Let me know if you need my help with anything

**Comment by nolim1t** [comment]
Its a bit hard to test because Im right now using my spare hardware (with raspbian) to sync up a node...

**Comment by nolim1t** [comment]
Also going to add some swap too (```/mnt/data/swap```) so it minimizes IO to the SD card

config is  ```/etc/dphys-swapfile ```

**Comment by nolim1t** [comment]
Im testing this with the latest version of umbrel-os now

**Comment by nolim1t** [comment]
I've run some of this on test hardware.. and yes pruning doesn't get disabled

**Comment by nolim1t** [comment]
I pushed the fix regarding pruning.

**Comment by nolim1t** [comment]
Can't seem to reproduce the symlink issue though

**Comment by nolim1t** [comment]
Also going to add https://github.com/getumbrel/umbrel-compose/pull/21 to this too

**Comment by nolim1t** [comment]
swapfile added

**Comment by nolim1t** [comment]
Think this is ready to merge initially so we don't hold up on other stuff (image related)

**Comment by mayankchhabra** [comment]
Great, I'll re-run the tests then

**Comment by nolim1t** [comment]
Also have another PR https://github.com/getumbrel/umbrel-compose/pull/22 for getting ready for lnd passwords (in testing now first)

**Comment by nolim1t** [comment]
with a default formatted fat32 drive

```
root@umbrel:/# /etc/rc.local 
Run partition tool or quit out if unavailable
USB Configuration script
Creating data mount
mount: /mnt/data: unknown filesystem type 'exfat'.
REKT file exists OR bitcoin folder not found... So lets format it
umount: /mnt/data: not mounted.
Initializing filesystem
mke2fs 1.44.5 (15-Dec-2018)
/dev/sda1 contains a exfat file system labelled 'Fat32 test'
Creating filesystem with 7510784 4k blocks and 1880480 inodes
Filesystem UUID: 95dbc66d-5348-4177-9cc3-524a553edd9c
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
	4096000

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done   

Pruning the config, because drive is less than 512 GB
Setup secrets, db, bitcoin, nginx, and lnd directory.. as a new install
Add swap to partition
Restarting dphys swapfile
[ ok ] Restarting dphys-swapfile (via systemctl): dphys-swapfile.service.
Unmounting partition
umount: /mnt/data: target is busy.
mount: /mnt/data: /dev/sda1 already mounted on /mnt/data.
Setup filesystem permissions (UID=1000 GID=1000)
Unmounting partition
umount: /mnt/data: target is busy.
Update /etc/fstab
Remounting through /bin/mount
Remove old folders (after copying)
Set up symlinks
Running rpcauth.py, and generating secrets for bitcoind
Updating bitcoin.conf
Service configured.. Checking for partitioned state
Set  up symlinks
Enabling defaults for umbrelbox
Enabling startup for umbrel box
Failed to enable unit: Unit /run/systemd/generator.late/umbrelbox.service is transient or generated.
starting up umbrelbox get it started now)
Starting
Pulling nginx (nginx:1.17.8)...
1.17.8: Pulling from library/nginx
fff3167bf8c7: Downloading [=========================>                         ] d7d79096e19b: Downloading [========================>                          ]  10.81MB/22.24MBwnload complete
    202B/202B
```

**Comment by nolim1t** [comment]
The above error is actually good news too.. it will format the drive if the filesystem is unknown to the PI (that is fat32 / ntfs / macOS).

and the swap goes in nicely

I will merge is in with master so everything can get nicely integrated.

We can tweak things later.

**Pull request merged**
