### PR TITLE
Use current working directory instead of home directory

### PR DESCRIPTION
**Pull request by nolim1t**
Use current working directory instead of home directory instead so its more portable.

### CODE REVIEW

**Comment by mayankchhabra** [comment]
ACK. It helps with the portability. Can we just remove `PWD` altogether? So for example, instead of making it `${PWD}/bitcoin`, we can leave it to just just `bitcoin` as we know `docker-compose.yml` is already in the current directory of all the mounted directories that use `PWD`

It would also work with the OTA update scripts out of the box, like this one, without the need to manually change `HOME` env as the scripts are run by root: https://github.com/getumbrel/umbrel-compose/blob/8d61be12f49adbb34c1a7507986939d003c942aa/update-scripts/install.sh#L34

Also before we merge this, some logic in the `umbrel-manager` will need to be updated, so we can't do this:
https://github.com/getumbrel/umbrel-compose/blob/089ad222ee92036d5dcdb3430903c17d231e66bb/docker-compose.yml#L59

**Comment by nolim1t** [comment]
> ACK. It helps with the portability. Can we just remove `PWD` altogether? So for example, instead of making it `${PWD}/bitcoin`, we can leave it to just just `bitcoin` as we know `docker-compose.yml` is already in the current directory of all the mounted directories that use `PWD`
> 
> It would also work with the OTA update scripts out of the box, like this one, without the need to manually change `HOME` env as the scripts are run by root:
> 
> https://github.com/getumbrel/umbrel-compose/blob/8d61be12f49adbb34c1a7507986939d003c942aa/update-scripts/install.sh#L34
> 
> Also before we merge this, some logic in the `umbrel-manager` will need to be updated, so we can't do this:
> 
> https://github.com/getumbrel/umbrel-compose/blob/089ad222ee92036d5dcdb3430903c17d231e66bb/docker-compose.yml#L59

what is the best way to handle that ```- ${PWD}:${PWD} ``` logic.. what was the purpose of doing that mapping?

**Comment by mayankchhabra** [comment]
Ok, it works perfectly with `PWD` now!

> what was the purpose of doing that mapping?

`umbrel-manager` needs access to the exact same directory + path for `docker-compose` to function inside its container as it manages the lifecycle of other containers - eg. restart lnd container to change password.

**Comment by nolim1t** [comment]
yeah it should work with ```PWD```

**Comment by nolim1t** [comment]
Throwing this patch away for now

**Comment by mayankchhabra** [comment]
Why? It worked pretty well for me with the changes you made!

**Comment by mayankchhabra** [comment]
Consider restoring the branch and merging it after you test it too.

**Comment by mayankchhabra** [comment]
Ah nevermind, just saw you moved it to #28

**Pull request closed without merging**
